mjd/apps/principal/urls.py
from django.conf.urls import url
from .views import PrincipalView
from . import views

app_name='principal'
urlpatterns = [
    url(r'^$',PrincipalView.as_view(),name='home_page'),
    url(r'^busqueda$', views.BusquedaEspecificaListView.as_view(), name='busqueda_especifica'),
    ################################
    url(r'^listar/busquedas$',views.BusquedaList.as_view(), name='busqueda_list'),# X
    url(r'^agregar/busqueda$', views.BusquedaCreate.as_view(), name='busqueda_new'),# X
    url(r'^editar/busqueda/(?P<pk>\d+)$', views.BusquedaUpdate.as_view(), name='busqueda_edit'),# X
    url(r'^borrar/busqueda/(?P<pk>\d+)$', views.BusquedaDelete.as_view(), name='busqueda_delete'),# X
    url(r'^resultados/busqueda/(?P<pk>\d+)$', views.BusquedaDetail.as_view(), name='busqueda_detail'),# X
    #####CRUD Cónfiguracion
    url(r'^listar/conf_home$',views.ConfiguracionHomeList.as_view(), name='conf_home_list'),# X
    url(r'^agregar/conf_home', views.ConfiguracionHomeCreate.as_view(), name='conf_home_new'),# X
    url(r'^editar/conf_home/(?P<pk>\d+)$', views.ConfiguracionHomeUpdate.as_view(), name='conf_home_edit'),# X
    url(r'^borrar/conf_home/(?P<pk>\d+)$', views.ConfiguracionHomeDelete.as_view(), name='conf_home_delete'),# X
    url(r'^resultados/conf_home/(?P<pk>\d+)$', views.ConfiguracionHomeDetail.as_view(), name='conf_home_detail'),# X
    #####CRUD SetImages
    url(r'^listar/images_home$',views.SetImagesHomeList.as_view(), name='setimageshome_list'),# X
    url(r'^agregar/images_home', views.SetImagesHomeCreate.as_view(), name='setimageshome_new'),# X
    url(r'^editar/images_home/(?P<pk>\d+)$', views.SetImagesHomeUpdate.as_view(), name='setimageshome_edit'),# X
    url(r'^borrar/images_home/(?P<pk>\d+)$', views.SetImagesHomeDelete.as_view(), name='setimageshome_delete'),# X
    url(r'^resultados/images_home/(?P<pk>\d+)$', views.SetImagesHomeDetail.as_view(), name='setimageshome_detail'),# X
    #################################
    url(r'^ubicacion-autocomplete/$',  views.UbicacionAutocompleteView.as_view(),name='ubicacion-autocomplete'),
]

mjd/apps/propiedad/urls.py
from django.conf.urls import url
from . import views


app_name='propiedad'
urlpatterns = [
    url(r'^listar/propietarios$',views.PropietarioList.as_view(), name='propietario_list'),
    url(r'^agregar/propietario$', views.PropietarioCreate.as_view(), name='propietario_new'),
    url(r'^editar/propietario/(?P<pk>\d+)$', views.PropietarioUpdate.as_view(), name='propietario_edit'),
    url(r'^borrar/propietario/(?P<pk>\d+)$', views.PropietarioDelete.as_view(), name='propietario_delete'),
    url(r'^propietario/(?P<pk>\d+)$', views.PropietarioDetail.as_view(), name='propietario_detail'),

    ################################
    url(r'^listar/arquitectos$',views.ArquitectoList.as_view(), name='arquitecto_list'),
    url(r'^agregar/arquitecto$', views.ArquitectoCreate.as_view(), name='arquitecto_new'),
    url(r'^editar/arquitecto/(?P<pk>\d+)$', views.ArquitectoUpdate.as_view(), name='arquitecto_edit'),
    url(r'^borrar/arquitecto/(?P<pk>\d+)$', views.ArquitectoDelete.as_view(), name='arquitecto_delete'),
    url(r'^arquitecto/(?P<pk>\d+)$', views.ArquitectoDetail.as_view(), name='arquitecto_detail'),
    #################################
    url(r'^listar/propiedades$',views.PropiedadList.as_view(), name='propiedad_list'),
    url(r'^agregar/propiedad$', views.PropiedadCreate.as_view(), name='propiedad_new'),
    url(r'^editar/propiedad/(?P<pk>\d+)$', views.PropiedadUpdate.as_view(), name='propiedad_edit'),
    url(r'^borrar/propiedad/(?P<pk>\d+)$', views.PropiedadDelete.as_view(), name='propiedad_delete'),
    url(r'^propiedad/(?P<pk>\d+)$', views.PropiedadDetail.as_view(), name='propiedad_detail'),
    ##Autocomplete urls
    url(r'^propietario-autocomplete/$',views.PropietarioAutocomplete.as_view( create_field = 'nombre' ), name='propietario-autocomplete'),
    url(r'^arquitecto-autocomplete/$',views.ArquitectoAutocomplete.as_view( create_field = 'nombre' ), name='arquitecto-autocomplete'),
    url(r'^propiedad-choices-autocomplete/$',views.PropiedadChoicesAutocomplete.as_view( ), name='propiedad-choices-autocomplete'),
    url(r'^caracter-choices-autocomplete/$',views.CaracterChoicesAutocomplete.as_view( ), name='caracter-choices-autocomplete'),
    url(r'^buscar/propiedad/?$', views.PropiedadSearchView.as_view(),name='haystack_buscar_propiedad'),
    ]

mjd/mjd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from django.contrib.sitemaps.views import sitemap
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),    
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    #url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^',include('apps.principal.urls', 
            namespace='principal')),
    url(r'^',include('apps.pagina.urls', 
            namespace='pagina')),
    url(r'^',include('apps.contactform.urls', 
            namespace='contact_form')),
    url(r'^',include('apps.propiedad.urls', 
            namespace='propiedad')),
    url(r'^',include('apps.localizacion.urls', 
            namespace='localizacion')),
    #url(r'^',include('apps.perfil.urls',namespace='perfil')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^buscar/', include('haystack.urls')),
    #url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^comments/', include('django_comments.urls')),
    #url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    #url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps}),
    #url(r'^accounts/', include('userena.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

mjd/apps/propiedad/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

from django.utils.translation import ugettext_lazy as _

from apps.localizacion.models import Localizacion

from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from django.urls import reverse
from django.contrib.auth.models import User


from crum import get_current_user





# Create your models here.
class Propietario(models.Model):
    nombre=models.CharField(max_length=100)
    website=models.URLField(max_length=300)
    email=models.EmailField()
    fono=models.PositiveIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    object_id = models.PositiveIntegerField(null=True, blank=True, editable=False)
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('propietario_detail', kwargs={'pk':self.pk})

    @property
    def Propietario(self):
        return self.__str__()


    class Meta:
        app_label = 'propiedad'
        verbose_name = _("Propietario")
        verbose_name_plural = _("Propietarios")
        ordering = ("nombre","website")

class Arquitecto(models.Model):
    nombre=models.CharField(max_length=100)
    website=models.URLField(max_length=300)
    email=models.EmailField()
    fono=models.PositiveIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    object_id = models.PositiveIntegerField(null=True, blank=True, editable=False)
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('arquitecto_detail', kwargs={'pk':self.pk})

    @property
    def Arquitecto(self):
        return self.__str__()


    class Meta:
        app_label = 'propiedad'
        verbose_name = _("Arquitecto")
        verbose_name_plural = _("Arquitectos")
        ordering = ("nombre","website")



class Propiedad(models.Model):
    CARACTER_CHOICES=(
        ('Buy','Vender'),
        ('Lease','Arrendar')
    )
    PROPIEDAD_CHOICES=(
        ("Depto","Departamento"),
        ("Casa","Casa"),
        ("Of","Oficina"),
        ("Sitio","Sitio"),
        ("Comerc","Comercial"),
        ("Ing","Industrial"),
        ("Agr","Agrícola"),
        ("Lot","Loteo"),
        ("Bod","Bodega"),
        ("Parc","Parcela"),
        ("Est","Estacionamiento"),
        ("Cons","Terreno en Construcción"),
    )
    ESTADO_CHOICES=(
        ('new','Nuevo'),
        ('used','Usado')
    )
    nombre=models.CharField(max_length=100)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='usuario_publica')
    #modificado = models.ForeignKey(User, related_name='usuario_modifica')
    estado = models.CharField(max_length=30, choices=ESTADO_CHOICES)
    caracter=models.CharField(max_length=100,choices=CARACTER_CHOICES)
    tipo_propiedad=models.CharField(max_length=100,choices=PROPIEDAD_CHOICES)
    fecha_registro=models.DateField(auto_now_add=True)
    #foreign key to comuna
    localizacion=models.ForeignKey(Localizacion, on_delete=models.CASCADE)
    #valores que se guardan en save, al hacer geocode
    #
    cantidad_dormitorios=models.PositiveSmallIntegerField()
    cantidad_baños=models.PositiveIntegerField()
    #=models.FloatField(help_text="Dimensión en metros [m], decimales con '.' ")
    #dimension_ancho=models.FloatField(help_text="Dimensión en metros [m], decimales con '.' ")
    area = models.FloatField(verbose_name='Área')
    descripcion= RichTextUploadingField(help_text="Describe a cabalidad la propiedad")
    #aspectos_destacables= RichTextUploadingField(help_text="Remarca los aspectos de mayor interés")
    fecha_entrega= models.DateField()
    propietario= models.ForeignKey(Propietario, blank=True, on_delete=models.CASCADE)
    arquitecto=models.ForeignKey(Arquitecto, blank=True, on_delete=models.CASCADE)
    en_oferta=models.BooleanField(default=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True, blank=True, editable=False)
    object_id = models.PositiveIntegerField(null=True, blank=True, editable=False)
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.nombre

    def get_tipo_propiedad(self):
        PC=dict(self.PROPIEDAD_CHOICES)
        return PC[self.tipo_propiedad]

    def get_absolute_url(self):
        return reverse('propiedad:propiedad_detail', kwargs={'pk':self.pk})

    @property
    def Busqueda(self):
        return self.__str__()

    def save(self, *args, **kwargs):
        user = get_current_user()
        if not self.usuario:
            self.usuario= user
        super(Propiedad, self).save(*args, **kwargs)

    class Meta:
        app_label = 'propiedad'
        verbose_name = _("Propiedad")
        verbose_name_plural = _("Propiedades")
        ordering = ("nombre","caracter","tipo_propiedad","fecha_registro")

# class LogSearchPropietadad(Propiedad):
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

class ImagenPropiedad(models.Model):
    imagen = models.ImageField(upload_to='propiedad/imagen')
    etiqueta = models.CharField(max_length=100)
    principal = models.BooleanField(default=False)
    propiedad = models.ForeignKey(Propiedad, related_name='imagen_propiedad', on_delete=models.CASCADE)
    imagen_thumbnail = ImageSpecField(source='imagen',
                                      processors=[ResizeToFill(300, 250)],
                                      format='JPEG',
                                      options={'quality': 60})
    def __str__(self):
        return self.etiqueta

    class Meta:
        app_label = 'propiedad'
        verbose_name = 'imagen'
        verbose_name_plural = 'imágenes'

class PrecioPropiedad(models.Model):
    MONEDA_CHOICES=(
        ("Peso","$"),
        ("Unidad de Fomento","U.F."),
        ("Dólar Americano","US$")
    )
    moneda = models.CharField(max_length=100,choices=MONEDA_CHOICES)
    cantidad = models.FloatField()
    propiedad = models.ForeignKey(Propiedad, related_name='precio_propiedad', on_delete=models.CASCADE)

    def __str__(self):
        return self.moneda +" "+ str(self.cantidad)

    class Meta:
        app_label = 'propiedad'
        verbose_name = _("Precio Propiedad")
        verbose_name_plural = _("Precios de Propiedades")
        #ordering = ("moneda","cantidad","propiedad.fecha_entrega")
        managed = True

mjd/apps/principal/forms.py
from django import forms
from django.forms import ModelForm
from .models import Busqueda
from tools.widgets.semantic_search import AutoCompleteSearchWidget
from apps.localizacion.models import Region, Comuna


class BusquedaForm ( ModelForm ):

    COMUNAS=[(comuna.pk, comuna.nombre) for comuna in Comuna.objects.all()]

    # the fields using this widgets enabled the semantic ui dropdown and search

    tipo_adquisicion=forms.ChoiceField(
        widget=AutoCompleteSearchWidget({
            'attrs':{'id':'tipo_adquisicion','name':"Tipo de Adquisición"},
            "choices":Busqueda.ADQUISICION_CHOICES
            })
        )
    tipo_propiedad=forms.ChoiceField(
        widget=AutoCompleteSearchWidget({
            'attrs':{'id':'tipo_propiedad','name':"Tipo de Propiedad"},
            "choices":Busqueda.PROPIEDAD_CHOICES
            })
        )
            
    estado=forms.ChoiceField(
        widget=AutoCompleteSearchWidget({
            'attrs':{'id':'estado','name':"Estado de propiedad"},
            "choices":Busqueda.ESTADO_CHOICES
            })
        )

    ubicacion=forms.ChoiceField(
        widget=AutoCompleteSearchWidget({
            'attrs':{'id':'ubicacion','name':'Ubicación'},
            "choices":COMUNAS
            })
        )

    # ubicacion =
    class Meta:
        model = Busqueda
        fields = [ 'tipo_adquisicion',
                   'tipo_propiedad',
                   'estado',
                   'ubicacion',
                   ]


    def __init__(self, *args, **kwargs):
        super(BusquedaForm,self).__init__(*args,**kwargs)
        print(self.fields)
        self.fields['tipo_adquisicion'].widget.attrs['class'] = "ui fluid search selection dropdown"
        self.fields['tipo_propiedad'].widget.attrs['class'] = "ui fluid search selection dropdown"
        self.fields['estado'].widget.attrs['class'] = "ui fluid search selection dropdown"
        self.fields['ubicacion'].widget.attrs['class'] = "ui fluid search selection dropdown"
        #self.fields['ubicacion'].widget.attrs['id'] = 'id_ubicacion'
        #self.fields['ubicacion'].widget.attrs.update({'class' : 'ui search dropdown  prop-form', 'id' :'id_ubicacion'})
        self.fields['tipo_adquisicion'].widget.attrs['placeholder'] = 'Tipo adquisición'
        #self.fields['ubicacion'].widget.attrs['placeholder'] = "Ubicación"
        #self.fields['email'].label = ""



from django.forms import formset_factory
from django.forms.models import inlineformset_factory

from .models import HomeImage, SetHomeImage
from djangoformsetjs.utils import formset_media_js


class SetHomeImagesForm ( ModelForm ):
    class Meta:
        model = SetHomeImage
        fields = [
            'nombre'
        ]
        js = formset_media_js + (
            # Other form media here
        )


HomeImageFormSet = inlineformset_factory ( SetHomeImage, HomeImage, fields=('imagen', 'etiqueta',),extra=1 )

mjd/apps/principal/templates/destacados.html
{% load imagekit %}
{% load static %}

{% if propiedades_destacadas %}
<div class="destacadas">

    <h1>Propiedades Destacadas:</h1>
        <link rel="stylesheet" type="text/css" href="{% static 'css/destacadas.css' %}">

<div class="ui special cards">
{% for destacada in propiedades_destacadas %}
        <div class="propiedad-destacada card">
            <a href="{% url 'propiedad:propiedad_detail' destacada.propiedad.pk %}">
                <div class="imagen-propiedad-destacada blurring dimmable image">                    
                      
                      <div class="ui dimmer">
                        <div class="content">
                          <div class="center">
                            <div class="ui inverted button">Ver Propiedad</div>
                          </div>
                        </div>
                      </div>

                    {% for img in destacada.propiedad.imagen_propiedad.all %}
                        {% if img.principal %}
                            {% generateimage 'mjd:destacada' source=img.imagen  %}
                        {% endif %}
                    {% endfor %}
            </div>
            </a>

                <div class="content">
                                <div class="oferta">

                <div class="precio">
                    {% for precio in destacada.propiedad.precio_propiedad.all %}
                        <div class="moneda">
                            {{ precio.get_moneda_display }}
                        </div>
                        <div class="valor">
                            {{ precio.cantidad }}
                        </div>
                    {% endfor %}
                </div>
            <div class="localizacion">
                <div class="ubicacion">
                    {{ destacada.propiedad.localizacion.direccion }}
                </div>
                <div class="comuna">
                    {{ destacada.propiedad.localizacion.comuna.nombre }}
                </div>
            </div>
            </div>


        </div>
    </div>
{% endfor %}
</div>
{% endif %}
<script type="text/javascript">
    $('.special.cards .image').dimmer({
  on: 'hover'
});    
</script>

mjd/apps/principal/templates/search_propiedad_form.html
{% load static %}
{% load imagekit %}
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
<section class="buscador">   

                        <!--end form-->
                                    <form method="GET" class="get-form ui fluid form segment" id="search_form" action="{% url 'principal:busqueda_especifica' %}">
                                        {{ form.non_field_errors }}
                                        <div class="fields">

                                            <div class="tipo-adquisicion three wide  field">
                                                {{ form.tipo_adquisicion.errors }}
                                                <label class="etiqueta" id="{{ form.tipo_adquisicion.id_for_label }}">Tipo de adquisión</label>
                                                {{ form.tipo_adquisicion }}
                                            </div>

                                            <div class="tipo-propiedad four wide  field">
                                                {{ form.tipo_propiedad.errors }}
                                                <label class="etiqueta"  id="{{ form.tipo_propiedad.id_for_label }}"> Tipo de propiedad</label>
                                                {{ form.tipo_propiedad }}
                                            </div>

                                            <div class="estado three wide  field">
                                                {{ form.estado.errors }}
                                                <label class="etiqueta"  id="{{ form.estado.id_for_label }}"> Estado </label>
                                                {{ form.estado }}
                                            </div>

                                            <div class="ubicacion four wide field">
                                                {{ form.ubicacion.errors }}
                                                <label class="etiqueta"  id="{{ form.ubicacion.id_for_label }}"> Ubicación </label>
                                                {{ form.ubicacion }}
                                            </div>

                                            <div id="search-submit-button" class="">
                                                    <button   id="s-button" class="big ui circular button" type="submit" > 
                                                    <i id="icon-s-button" class="big search icon"></i>
                                                </button>
                                            </div>

                                        </div>

                                    </form>

</section>
<script type="text/javascript">
$('.ui.dropdown')
  .dropdown()
;
  </script>