mjd/apps/contactform/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

app_name='contact_form'
urlpatterns = [
    url(r'^contacto/$', views.formulario_contacto, name= 'formulario_contacto'),
]

mjd/apps/principal/urls.py
from django.conf.urls import url
from .views import PrincipalView
from . import views

app_name='principal'
urlpatterns = [
    url(r'^$',PrincipalView.as_view(),name='home_page'),
    url(r'^busqueda$', views.BusquedaEspecificaListView.as_view(), name='busqueda_especifica'),
    ################################
    url(r'^listar/busquedas$',views.BusquedaList.as_view(), name='busqueda_list'),# X
    url(r'^agregar/busqueda$', views.BusquedaCreate.as_view(), name='busqueda_new'),# X
    url(r'^editar/busqueda/(?P<pk>\d+)$', views.BusquedaUpdate.as_view(), name='busqueda_edit'),# X
    url(r'^borrar/busqueda/(?P<pk>\d+)$', views.BusquedaDelete.as_view(), name='busqueda_delete'),# X
    url(r'^resultados/busqueda/(?P<pk>\d+)$', views.BusquedaDetail.as_view(), name='busqueda_detail'),# X
    #####CRUD Cónfiguracion
    url(r'^listar/conf_home$',views.ConfiguracionHomeList.as_view(), name='conf_home_list'),# X
    url(r'^agregar/conf_home', views.ConfiguracionHomeCreate.as_view(), name='conf_home_new'),# X
    url(r'^editar/conf_home/(?P<pk>\d+)$', views.ConfiguracionHomeUpdate.as_view(), name='conf_home_edit'),# X
    url(r'^borrar/conf_home/(?P<pk>\d+)$', views.ConfiguracionHomeDelete.as_view(), name='conf_home_delete'),# X
    url(r'^resultados/conf_home/(?P<pk>\d+)$', views.ConfiguracionHomeDetail.as_view(), name='conf_home_detail'),# X
    #####CRUD SetImages
    url(r'^listar/images_home$',views.SetImagesHomeList.as_view(), name='setimageshome_list'),# X
    url(r'^agregar/images_home', views.SetImagesHomeCreate.as_view(), name='setimageshome_new'),# X
    url(r'^editar/images_home/(?P<pk>\d+)$', views.SetImagesHomeUpdate.as_view(), name='setimageshome_edit'),# X
    url(r'^borrar/images_home/(?P<pk>\d+)$', views.SetImagesHomeDelete.as_view(), name='setimageshome_delete'),# X
    url(r'^resultados/images_home/(?P<pk>\d+)$', views.SetImagesHomeDetail.as_view(), name='setimageshome_detail'),# X
    #################################
    url(r'^ubicacion-autocomplete/$',  views.UbicacionAutocompleteView.as_view(),name='ubicacion-autocomplete'),
]

mjd/mjd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

from django.contrib.sitemaps.views import sitemap
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),    
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    #url(r'^admin_tools/', include('admin_tools.urls')),
    url(r'^',include('apps.principal.urls', 
            namespace='principal')),
    url(r'^',include('apps.pagina.urls', 
            namespace='pagina')),
    url(r'^',include('apps.contactform.urls', 
            namespace='contact_form')),
    url(r'^',include('apps.propiedad.urls', 
            namespace='propiedad')),
    url(r'^',include('apps.localizacion.urls', 
            namespace='localizacion')),
    #url(r'^',include('apps.perfil.urls',namespace='perfil')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^buscar/', include('haystack.urls')),
    #url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^comments/', include('django_comments.urls')),
    #url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    #url(r'^sitemap-(?P<section>.+)\.xml$', sitemap, {'sitemaps': sitemaps}),
    #url(r'^accounts/', include('userena.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

mjd/files/templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">


        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">


        <link rel="stylesheet" type="text/css" href="{% static "semantic/semantic.min.css" %}">
        <script src="{% static "js/jquery.min.js" %}"></script>
        <script src="{% static "semantic/semantic.min.js" %}"></script>

        {% block head_css %}

        {% endblock %}
        {% block head_javascript %}

        {% endblock %}

    </head>
    <body>


<div class="flaghome">
	<section class="base-header">
	    <header class="base-navbar">
	    	<div class="container">
	    {% block navbar %}
		    	<div class="row">
		    		<article class="base-top">
		    			<div class="row">
					    		<div class="base-logotipo">
								    {% block logo_header %}
								        <a href="{% url 'principal:home_page' %}">
								            <img class="base-logo " src="{% static 'site/logo.png' %}" alt="logo-corredora">
								        </a>
								    {% endblock %}
								 </div>

                            <div class="ui container">
                                <div class="ui five item menu">
                                     <a  href="/" class="active item base-last-properties">  Inicio</a>
                                     <a  href="/listar/propiedades" class="item base-last-properties">  Propiedades</a>                              
                                     <a  href="/pagina/mision" class="item base-mision">  Misión</a>
                                                                                         
                                     <a  href="/pagina/nuestra-historia" class="item base-historia">  Nuestra Historia</a> 

                                    <a  href="{% url 'contact_form:formulario_contacto' %}" class="item contacto">Contacto</a>


                                </div>
                            </div>

						</div>
					 </article>
				</div>
			</div>
	    </header>
	</section> 
	
	        {% block buscador %}

	        {% endblock buscador %}

	    {% endblock %}
	
</div>
    <section class="central-content">
     	{% block content %}
    	{% endblock %}
    </section>
        
<!-- /container -->

          <footer>
    {% include 'contacto.html' %}

          </footer>



        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>





{% block footer_javascript %}
{% endblock %}
{% block footer_styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
{% endblock %}



    </body>
</html>

mjd/files/templates/contacto.html
{% load static %}
<div class="ui">
<div class="data-contacto">

	<div class="ui container">
		<div class="ui stackable two column grid">

		<div id="texts-contacto" class="column">
	      <div class="nombre"><span>María José Durán Propiedades</span></div>
	      <div class="direccion"><span>José Martinez 320 of. 403</span>,<span>, Providencia</span></div>
	      <div class="telefono"><span>Teléfono: 2354317 - Fax: 2254318</span>, <span>e-mail: contacto@mjd.cl</span></div>
	      <!--<div class="web"><span>http://www.mariajoseduranpropiedades.cl</span></div>-->
	   </div>

		<div id="social-networks" class="column">

		        <button class="ui circular facebook icon button">
		          <i class="facebook icon"></i>
		        </button>
		        <button class="ui circular twitter icon button">
		          <i class="twitter icon"></i>
		        </button>
		        <button class="ui circular google plus icon button">
		          <i class="google plus icon"></i>
		        </button>
		        <button class="ui circular linkedin icon button">
		          <i class="linkedin icon"></i>
		        </button>
		</div>
	</div>

	</div>

</div>


</div>
  {% block footer_javascript %}
        {{form.media}}
{% endblock %}